### ISSUE TITLE
Search doesn't work properly from a technology page

### ISSUE THREAD

**Issue by dmelazo-cit** [ciandt-dev/tech-gallery#178]
Search only work from a Tech Gallery "home" page.

**Comment by brunocarneiro** [comment]
@dmelazo-cit What is the scenario? How do I simulate?

**Comment by dmelazo-cit** [comment]
Select any technology and enter the page detailing it. After do that, search another technology using the field above.

To simulate:
1. Enter this link http://techgallery.ciandt.com/#/technologies/docker
2. Input another technology to search ("WCF" for example).
3. Nothing happens.

**Comment by vitorluis** [comment]
The same happened to me. But I did on Android using Google Chrome

**Comment by marlonlima** [comment]
This bug was not fixed. It will be prioritized.

**Comment by ltogniolli** [comment]
Fixed by PR #208
