### ISSUE TITLE
Auto-avaliações erradas

### ISSUE THREAD

**Issue by asouza-cit** [ciandt-dev/tech-gallery#186]
Constatei que haviam auto-avaliações minhas em tecnologias que eu realmente não fiz a auto-avaliação por não conhecê-las, como por exemplo a WebGL. Eu nem ao menos tinha entrado nesse card para ver sobre o que era a tecnologia. E também não é possível editar a informação para remover a avaliação, no caso.

**Comment by ltogniolli** [comment]
As auto-avaliações foram importadas de uma pesquisa que fizemos algum tempo atrás no lançamento do radar original. Você deve ter respondido naquela época.

Realmente não dá para remover a avaliação no momento..

**Comment by ltogniolli** [comment]
Algora é possível remover a auto avaliação!
