### ISSUE TITLE
Possibilidade de se desmarcar de uma tecnologia, e esta não aparecer no seu profile.

### ISSUE THREAD

**Issue by patrikpicoli** [ciandt-dev/tech-gallery#189]
Notei que várias tecnologias em que só entrei já marcou como  "newbe", e estas aparecem agora no profile. Existe a possibilidade de se desmarcar de uma tecnologia para parar de aparecer no profile?

Detalhe para ajudar na resolução, fui abrindo em várias abas.

Desde já obrigado.

**Comment by patrikpicoli** [comment]
Respondifdo na issue #187, vou fechar.

**Comment by ltogniolli** [comment]
Agora é possível desmarcar...
