### ISSUE TITLE
Technology Images (logos) in daily emails should be styled as they appear on the web.

### ISSUE THREAD

**Issue by larruda** [ciandt-dev/tech-gallery#193]
They should be all the same size and within a circle, just like they appear on technology listing page.

![screen shot 2016-01-25 at 18 22 06](https://cloud.githubusercontent.com/assets/1940532/12563267/935d7ba8-c390-11e5-928c-d8876ab48f2a.png)

**Comment by ltogniolli** [comment]
Should be resolved!
